version: 2

collectors:
  in:
    type: shell
    params:
      interval: 1
    topics:
      temp: "echo '{ \"temp\": 23.5, \"ts\":' $(date +%s) '}'"
  file:
    type: file
    params:
      interval: 10
    topics:
      uptime: "/proc/uptime"

sinks:
  stdout:
    type: stdout

pipelines:
  - name: process_uptime
    topics:
      - uptime
    bus_mode: volatile
    parser:
      type: regex
      vars:
        uptime: "^(\\d+\\.\\d+)\\s"
    transform:
      uptime: "int(float(uptime))"

  - name: process_temp
    topics:
      - temp
    bus_mode: volatile
    parser:
      type: jsonpath
      vars:
        temp: "$.temp"
        ts:   "$.ts"
    transform:
      temp: "temp * 10"
      ts: "int(ts)"

  - name: report
    stateful: true
    type: cron
    schedule: "0/1 * * * * *" # Every second
    topics:
      - process_uptime
      - process_temp
    sinks:
      - name: stdout
        format: expr
        spec: |
          {
            "uptime": uptime ?? 0,
            "temp": temp,
            "ts": ts,
            "now": now()
          }
      - name: stdout
        format: template
        spec: |
          Uptime: {{ .uptime }}s, Temp: {{ .temp }}°C, Timestamp: {{ printf "%.0f" .ts }}, Now: {{ now "2006-01-02 15:04:05" }}
