version: 2

collectors:
  in:
    type: shell
    params:
      interval: 1
    topics:
      temp: "echo '{ \"temp\": 23.5, \"ts\":' $(date +%s) '}'"
  file:
    type: file
    params:
      interval: 10
    topics:
      uptime: "/proc/uptime"

sinks:
  stdout:
    type: stdout

pipelines:
  - name: process_uptime
    topics:
      - uptime
    bus_mode: volatile
    parser:
      type: regex
      vars:
        uptime: "^(\\d+\\.\\d+)\\s"
    transform:
      uptime: "int(float(uptime))"
    sinks:
      - name: stdout
        format: expr
        spec: '{ "uptime_seconds": uptime }'
  - name: process_temp
    topics:
      - temp
    bus_mode: volatile
    parser:
      type: jsonpath
      vars:
        temp: "$.temp"
        ts:   "$.ts"
    transform:
      temp: "temp * 10"
    sinks:
      - name: stdout
        format: expr
        spec: '{ "temperature": temp, "timestamp": ts }'
