version: 2

collectors:
  mqtt:
    type: mqtt
    params:
      url: ssl://mqtt:8883
      user: user
      pass: pass

sinks:
  stdout:
    type: stdout

pipelines:
  - name: process_outside_weather
    from: mqtt
    source_topic: "/topic1"
    bus_mode: volatile
    parser:
      type: jsonpath
      vars:
        temp: "$.temp"
    transform:
      temp: "temp * 10"
    dispatch:
      type: event
      sinks:
        - name: stdout
          format: expr
          spec: '{ "temperature": temp }'
