package windy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/mekops-labs/siphon/pkg/bus"
	"github.com/mekops-labs/siphon/pkg/sink"
	"github.com/mitchellh/mapstructure"
)

var windyAPIURL = "https://stations.windy.com/pws/update/"

type windyParams struct {
	ApiKey string `mapstructure:"apikey"`
	ID     int    `mapstructure:"id"` // Station ID (usually 0)
}

type windySink struct {
	params windyParams
	client *http.Client
}

// Ensure windySink implements sink.Sink
var _ sink.Sink = (*windySink)(nil)

func init() {
	sink.Registry.Add("windy", New)
}

func New(params any, _ bus.Bus) (sink.Sink, error) {
	var opt windyParams
	if err := mapstructure.Decode(params, &opt); err != nil {
		return nil, fmt.Errorf("failed to decode windy params: %w", err)
	}

	if opt.ApiKey == "" {
		return nil, fmt.Errorf("windy requires an apikey")
	}

	return &windySink{
		params: opt,
		client: &http.Client{Timeout: 10 * time.Second},
	}, nil
}

func (s *windySink) Send(b []byte) error {
	// 1. Unmarshal the incoming metrics generated by the pipeline expr
	var payload map[string]interface{}
	if err := json.Unmarshal(b, &payload); err != nil {
		return fmt.Errorf("windy sink failed to parse incoming payload: %w", err)
	}

	// 2. Inject the station ID required by Windy API
	payload["station"] = s.params.ID

	// 3. Re-marshal
	finalBytes, err := json.Marshal(payload)
	if err != nil {
		return err
	}

	// Windy's PWS Update endpoint
	targetURL := fmt.Sprintf(windyAPIURL+"%s", s.params.ApiKey)

	req, err := http.NewRequest(http.MethodPost, targetURL, bytes.NewReader(finalBytes))
	if err != nil {
		return err
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := s.client.Do(req)
	if err != nil {
		return fmt.Errorf("windy request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("windy returned non-2xx status: %d", resp.StatusCode)
	}

	return nil
}
