package modules

//go:generate go run ../../tools/genmodules
// Code generated by tools/genmodules; DO NOT EDIT.

import (
	_ "github.com/mekops-labs/siphon/pkg/collector/file"
	_ "github.com/mekops-labs/siphon/pkg/collector/hass"
	_ "github.com/mekops-labs/siphon/pkg/collector/mqtt"
	_ "github.com/mekops-labs/siphon/pkg/collector/rest"
	_ "github.com/mekops-labs/siphon/pkg/collector/shell"
	_ "github.com/mekops-labs/siphon/pkg/collector/webhook"
	_ "github.com/mekops-labs/siphon/pkg/parser/jsonpath"
	_ "github.com/mekops-labs/siphon/pkg/parser/regex"
	_ "github.com/mekops-labs/siphon/pkg/sink/bus"
	_ "github.com/mekops-labs/siphon/pkg/sink/gotify"
	_ "github.com/mekops-labs/siphon/pkg/sink/iotplotter"
	_ "github.com/mekops-labs/siphon/pkg/sink/ntfy"
	_ "github.com/mekops-labs/siphon/pkg/sink/stdout"
	_ "github.com/mekops-labs/siphon/pkg/sink/windy"
)
